DELIMITER //

CREATE PROCEDURE NOW3 ()
BEGIN
  DECLARE i INT DEFAULT 3;
  WHILE i > 0 DO
    SELECT NOW();
    SET i = i - 1;
  END WHILE;
END//

CALL NOW3()//

DROP PROCEDURE IF EXISTS NOW3//
CREATE PROCEDURE NOW3 ()
BEGIN
  DECLARE i INT DEFAULT 3;
  REPEAT
    SELECT NOW();
    SET i = i - 1;
  UNTIL i <= 0
  END REPEAT;
END//

CALL NOW3()//

DROP PROCEDURE IF EXISTS NOW3//
CREATE PROCEDURE NOW3 ()
BEGIN
  DECLARE i INT DEFAULT 3;
  cycle: LOOP
    SELECT NOW();
    SET i = i - 1;
    IF i <= 0 THEN LEAVE cycle;
    END IF;
  END LOOP cycle;
END//

CALL NOW3()//